# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'home.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(777, 498)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(350, 420, 101, 39))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(220, 70, 371, 20))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(190, 30, 431, 17))
        font = QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label_2.setFont(font)
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(60, 110, 71, 39))
        self.lineEdit_2 = QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(60, 170, 71, 39))
        self.lineEdit_3 = QLineEdit(self.centralwidget)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(60, 230, 71, 39))
        self.lineEdit_4 = QLineEdit(self.centralwidget)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(60, 290, 71, 39))
        self.lineEdit_5 = QLineEdit(self.centralwidget)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(60, 350, 71, 39))
        self.lineEdit_6 = QLineEdit(self.centralwidget)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(180, 350, 71, 39))
        self.lineEdit_7 = QLineEdit(self.centralwidget)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(180, 230, 71, 39))
        self.lineEdit_8 = QLineEdit(self.centralwidget)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(180, 170, 71, 39))
        self.lineEdit_9 = QLineEdit(self.centralwidget)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(180, 110, 71, 39))
        self.lineEdit_10 = QLineEdit(self.centralwidget)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(180, 290, 71, 39))
        self.lineEdit_11 = QLineEdit(self.centralwidget)
        self.lineEdit_11.setObjectName(u"lineEdit_11")
        self.lineEdit_11.setGeometry(QRect(300, 350, 71, 39))
        self.lineEdit_12 = QLineEdit(self.centralwidget)
        self.lineEdit_12.setObjectName(u"lineEdit_12")
        self.lineEdit_12.setGeometry(QRect(300, 230, 71, 39))
        self.lineEdit_13 = QLineEdit(self.centralwidget)
        self.lineEdit_13.setObjectName(u"lineEdit_13")
        self.lineEdit_13.setGeometry(QRect(300, 170, 71, 39))
        self.lineEdit_14 = QLineEdit(self.centralwidget)
        self.lineEdit_14.setObjectName(u"lineEdit_14")
        self.lineEdit_14.setGeometry(QRect(300, 110, 71, 39))
        self.lineEdit_15 = QLineEdit(self.centralwidget)
        self.lineEdit_15.setObjectName(u"lineEdit_15")
        self.lineEdit_15.setGeometry(QRect(300, 290, 71, 39))
        self.lineEdit_16 = QLineEdit(self.centralwidget)
        self.lineEdit_16.setObjectName(u"lineEdit_16")
        self.lineEdit_16.setGeometry(QRect(660, 350, 71, 39))
        self.lineEdit_17 = QLineEdit(self.centralwidget)
        self.lineEdit_17.setObjectName(u"lineEdit_17")
        self.lineEdit_17.setGeometry(QRect(420, 350, 71, 39))
        self.lineEdit_18 = QLineEdit(self.centralwidget)
        self.lineEdit_18.setObjectName(u"lineEdit_18")
        self.lineEdit_18.setGeometry(QRect(420, 230, 71, 39))
        self.lineEdit_19 = QLineEdit(self.centralwidget)
        self.lineEdit_19.setObjectName(u"lineEdit_19")
        self.lineEdit_19.setGeometry(QRect(540, 110, 71, 39))
        self.lineEdit_20 = QLineEdit(self.centralwidget)
        self.lineEdit_20.setObjectName(u"lineEdit_20")
        self.lineEdit_20.setGeometry(QRect(660, 170, 71, 39))
        self.lineEdit_21 = QLineEdit(self.centralwidget)
        self.lineEdit_21.setObjectName(u"lineEdit_21")
        self.lineEdit_21.setGeometry(QRect(420, 170, 71, 39))
        self.lineEdit_22 = QLineEdit(self.centralwidget)
        self.lineEdit_22.setObjectName(u"lineEdit_22")
        self.lineEdit_22.setGeometry(QRect(540, 230, 71, 39))
        self.lineEdit_23 = QLineEdit(self.centralwidget)
        self.lineEdit_23.setObjectName(u"lineEdit_23")
        self.lineEdit_23.setGeometry(QRect(540, 290, 71, 39))
        self.lineEdit_24 = QLineEdit(self.centralwidget)
        self.lineEdit_24.setObjectName(u"lineEdit_24")
        self.lineEdit_24.setGeometry(QRect(660, 110, 71, 39))
        self.lineEdit_25 = QLineEdit(self.centralwidget)
        self.lineEdit_25.setObjectName(u"lineEdit_25")
        self.lineEdit_25.setGeometry(QRect(540, 170, 71, 39))
        self.lineEdit_26 = QLineEdit(self.centralwidget)
        self.lineEdit_26.setObjectName(u"lineEdit_26")
        self.lineEdit_26.setGeometry(QRect(660, 290, 71, 39))
        self.lineEdit_27 = QLineEdit(self.centralwidget)
        self.lineEdit_27.setObjectName(u"lineEdit_27")
        self.lineEdit_27.setGeometry(QRect(420, 110, 71, 39))
        self.lineEdit_28 = QLineEdit(self.centralwidget)
        self.lineEdit_28.setObjectName(u"lineEdit_28")
        self.lineEdit_28.setGeometry(QRect(660, 230, 71, 39))
        self.lineEdit_29 = QLineEdit(self.centralwidget)
        self.lineEdit_29.setObjectName(u"lineEdit_29")
        self.lineEdit_29.setGeometry(QRect(540, 350, 71, 39))
        self.lineEdit_30 = QLineEdit(self.centralwidget)
        self.lineEdit_30.setObjectName(u"lineEdit_30")
        self.lineEdit_30.setGeometry(QRect(420, 290, 71, 39))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 120, 31, 17))
        font1 = QFont()
        font1.setPointSize(14)
        self.label_3.setFont(font1)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 180, 31, 17))
        self.label_4.setFont(font1)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 240, 31, 17))
        self.label_5.setFont(font1)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 300, 31, 17))
        self.label_6.setFont(font1)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 360, 31, 17))
        self.label_7.setFont(font1)
        self.label_7.setAlignment(Qt.AlignCenter)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(140, 120, 31, 17))
        self.label_8.setFont(font1)
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(140, 180, 31, 17))
        self.label_9.setFont(font1)
        self.label_9.setAlignment(Qt.AlignCenter)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(140, 240, 31, 17))
        self.label_10.setFont(font1)
        self.label_10.setAlignment(Qt.AlignCenter)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(140, 300, 31, 17))
        self.label_11.setFont(font1)
        self.label_11.setAlignment(Qt.AlignCenter)
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(140, 360, 31, 17))
        self.label_12.setFont(font1)
        self.label_12.setAlignment(Qt.AlignCenter)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(260, 120, 31, 17))
        self.label_13.setFont(font1)
        self.label_13.setAlignment(Qt.AlignCenter)
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(260, 180, 31, 17))
        self.label_14.setFont(font1)
        self.label_14.setAlignment(Qt.AlignCenter)
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(260, 240, 31, 17))
        self.label_15.setFont(font1)
        self.label_15.setAlignment(Qt.AlignCenter)
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(260, 300, 31, 17))
        self.label_16.setFont(font1)
        self.label_16.setAlignment(Qt.AlignCenter)
        self.label_17 = QLabel(self.centralwidget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(260, 360, 31, 17))
        self.label_17.setFont(font1)
        self.label_17.setAlignment(Qt.AlignCenter)
        self.label_18 = QLabel(self.centralwidget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(380, 120, 31, 17))
        self.label_18.setFont(font1)
        self.label_18.setAlignment(Qt.AlignCenter)
        self.label_19 = QLabel(self.centralwidget)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(380, 180, 31, 17))
        self.label_19.setFont(font1)
        self.label_19.setAlignment(Qt.AlignCenter)
        self.label_20 = QLabel(self.centralwidget)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(380, 240, 31, 17))
        self.label_20.setFont(font1)
        self.label_20.setAlignment(Qt.AlignCenter)
        self.label_21 = QLabel(self.centralwidget)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(380, 300, 31, 17))
        self.label_21.setFont(font1)
        self.label_21.setAlignment(Qt.AlignCenter)
        self.label_22 = QLabel(self.centralwidget)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(380, 360, 31, 17))
        self.label_22.setFont(font1)
        self.label_22.setAlignment(Qt.AlignCenter)
        self.label_23 = QLabel(self.centralwidget)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(500, 120, 31, 17))
        self.label_23.setFont(font1)
        self.label_23.setAlignment(Qt.AlignCenter)
        self.label_24 = QLabel(self.centralwidget)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(500, 180, 31, 17))
        self.label_24.setFont(font1)
        self.label_24.setAlignment(Qt.AlignCenter)
        self.label_25 = QLabel(self.centralwidget)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(500, 240, 31, 17))
        self.label_25.setFont(font1)
        self.label_25.setAlignment(Qt.AlignCenter)
        self.label_26 = QLabel(self.centralwidget)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(500, 300, 31, 17))
        self.label_26.setFont(font1)
        self.label_26.setAlignment(Qt.AlignCenter)
        self.label_27 = QLabel(self.centralwidget)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(500, 360, 31, 17))
        self.label_27.setFont(font1)
        self.label_27.setAlignment(Qt.AlignCenter)
        self.label_28 = QLabel(self.centralwidget)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(620, 120, 31, 17))
        self.label_28.setFont(font1)
        self.label_28.setAlignment(Qt.AlignCenter)
        self.label_29 = QLabel(self.centralwidget)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(620, 180, 31, 17))
        self.label_29.setFont(font1)
        self.label_29.setAlignment(Qt.AlignCenter)
        self.label_30 = QLabel(self.centralwidget)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(620, 240, 31, 17))
        self.label_30.setFont(font1)
        self.label_30.setAlignment(Qt.AlignCenter)
        self.label_31 = QLabel(self.centralwidget)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(620, 300, 31, 17))
        self.label_31.setFont(font1)
        self.label_31.setAlignment(Qt.AlignCenter)
        self.label_32 = QLabel(self.centralwidget)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(620, 360, 31, 17))
        self.label_32.setFont(font1)
        self.label_32.setAlignment(Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Proses", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"  Harap masukkan masing-masing nilai dari 30 data yang ada", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"PENGHITUNGAN DATA STATISTIK", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"8", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"9", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"12", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"13", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"14", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"15", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"16", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"17", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"18", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"19", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"20", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"21", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"22", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"23", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"24", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"25", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"26", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"27", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"28", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"29", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"30", None))
    # retranslateUi

